version: '3'
services:
  solr:
    image: solr:8.1.1
    environment:
      - SOLR_OPTS=-Dsolr.jetty.request.header.size=65535
    volumes:
      - ${WEBAPP_STORAGE_HOME}/solr-sitecore-configsets:/opt/solr/server/solr/configsets
      - ${WEBAPP_STORAGE_HOME}/solr-sitecore-data:/var/solr/data
    command: 
      - bash
      - '-c'
      - 'curl https://raw.githubusercontent.com/raghumahesh50/solr-8.1.1-docker/master/sitecore-solr-8.1.1-configsets.zip -o /opt/solr/server/solr/configsets/configsets.zip && 
        unzip -o /opt/solr/server/solr/configsets/configsets.zip -d /opt/solr/server/solr/configsets && 
        wget -nc https://raw.githubusercontent.com/raghumahesh50/solr-8.1.1-docker/master/security.json -O /var/solr/data/security.json || true && 
        precreate-core sitecore_core_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_master_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_web_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_marketingdefinitions_master /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_marketingdefinitions_web /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_marketing_asset_index_master /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_marketing_asset_index_web /opt/solr/server/solr/configsets/sitecore &&
        precreate-core Sitecore-sitecore_testing_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core Sitecore-sitecore_suggested_test_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_personalization_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_fxm_master_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core sitecore_fxm_web_index /opt/solr/server/solr/configsets/sitecore &&
        precreate-core xdb /opt/solr/server/solr/configsets/xconnect &&
        precreate-core xdb_rebuild /opt/solr/server/solr/configsets/xconnect &&
        solr-foreground'